[package]
name = "Kernel"
version = "0.1.0"
authors = ["KeyboardMayCry <eddy199883@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]

# Target specified crate
[target.x86_64-sillyos.dependencies]
x86_64 = { path = "Platform/x86_64"}


