[package]
name = "Kernel"
version = "0.1.0"
authors = ["KeyboardMayCry <eddy199883@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]

# Target specificed crate
[target.x86_64-sillyos.dependencies]
x86 = "0.8.1"


